### ISSUE TITLE
Looks like CI does not support Python2

### ISSUE THREAD

**Issue by stardrewer** [asdf2014/algorithm#108]
https://github.com/asdf2014/algorithm/runs/3411179363#step:5:11

https://github.com/asdf2014/algorithm/blob/e01027e2790aab575eba8d3f2d42fdacd25fe596/Codes/fengxuanmo/leetcode/editor/cn/%5B%E5%89%91%E6%8C%87%20Offer%20II%20001%5D%E6%95%B4%E6%95%B0%E9%99%A4%E6%B3%95.py#L85

**Comment by asdf2014** [comment]
@fengxuanmo @fengkai Please take a look at the problem in CI system. You might need to use Python3 instead of Python2 to avoid it. FYI, https://github.com/asdf2014/algorithm/runs/3421131639. BTW, thanks @stardrewer for this report.
