### ISSUE TITLE
Help me enhance these Python code

### ISSUE THREAD

**Issue by asdf2014** [asdf2014/algorithm#28]
![E3436AE6-9233-4830-85F7-E62CB58EB2A5](https://user-images.githubusercontent.com/8108788/63211737-02bb5a80-c12e-11e9-8679-ab6400a3537b.jpeg)
![0C958A55-79DC-4067-BDE6-FD6EA356751E](https://user-images.githubusercontent.com/8108788/63211738-0353f100-c12e-11e9-9a95-2fd8d47cb43e.jpeg)
![55499CFD-27E0-496D-B7E4-49B7B91EAABE](https://user-images.githubusercontent.com/8108788/63211739-03ec8780-c12e-11e9-8d34-5278e4576fcd.jpeg)

@GinRyan Please help me enhance these Python code

**Comment by GinRyan** [comment]
Already fixed.
