### ISSUE TITLE
Call to function addTwoNumbers with too few arguments; should be no fewer than 2

### ISSUE THREAD

**Issue by asdf2014** [asdf2014/algorithm#36]
@XuanmoFeng Please help me to fix this.

![907111B8-1C4E-416E-AB05-9418DD9913FE](https://user-images.githubusercontent.com/8108788/64916702-d9d1c800-d7b4-11e9-8882-269ca028da38.jpeg)

**Comment by XuanmoFeng** [comment]
done

**Comment by XuanmoFeng** [comment]
done

**Comment by asdf2014** [comment]
@XuanmoFeng Thanks a lot :+1:
