### ISSUE TITLE
Please enhance these golang code

### ISSUE THREAD

**Issue by asdf2014** [asdf2014/algorithm#43]
@zsdostar Please enhance these golang code, more details: https://goreportcard.com/report/github.com/asdf2014/algorithm

![image](https://user-images.githubusercontent.com/8108788/65112213-1dbd0b00-da09-11e9-8223-a2db7278e6cb.png)

**Comment by zsdostar** [comment]
Received, I will enhance them recently

Thanks a lot for code review

**Comment by asdf2014** [comment]
Thanks for the quick fix! :+1:
