### ISSUE TITLE
Please enhance these python code

### ISSUE THREAD

**Issue by asdf2014** [asdf2014/algorithm#52]
@alphadl Please enhance these python code, more details: https://lgtm.com/projects/g/asdf2014/algorithm/alerts/?mode=list

![F086ADE7-A229-4D15-B7A2-F5A8F92DE970](https://user-images.githubusercontent.com/8108788/69471091-9f009780-0dd6-11ea-8167-74f2d28c712e.jpeg)

**Comment by alphadl** [comment]
fixed

**Comment by asdf2014** [comment]
@alphadl Thanks :+1:
