### ISSUE TITLE
Help me delete the branch "revert-62-master" created by my misoperation

### ISSUE THREAD

**Issue by zsdostar** [asdf2014/algorithm#63]
🤣求大佬帮忙删下误建出来的分支 @asdf2014 

 commit author 忘改了，提了个名字上去，在 master 上 rebase 改历史不太好

想看看 revert 和 Gitlab 的行为是不是一样的，结果直接创建个分支出来

**Comment by asdf2014** [comment]
好的好的，已删除

**Comment by zsdostar** [comment]
非常感谢！ _(:з」∠)_
