### ISSUE TITLE
first_commit.sh文件中的一些报错

### ISSUE THREAD

**Issue by Oh-MyBug** [asdf2014/algorithm#76]
```bash
bash: line 21: bc: command not found
Please set SSH to github!
bash: line 25: open: command not found
```
我配置了SSH，但是在git bash命令行中提示没有 `bc` 和 `open` 命令，需要怎么解决呢？

**Comment by asdf2014** [comment]
@Oh-MyBug 这是 Unix-like 的系统下的命令，如果你是 Windows 环境的话，可能需要用到 PowerShell 工具

**Comment by Oh-MyBug** [comment]
> @Oh-MyBug 这是 Unix-like 的系统下的命令，如果你是 Windows 环境的话，可能需要用到 PowerShell 工具

是的，我自己在本地创建了一个first_commit.sh文件，跳过了SSH检验，成功提交了，谢谢你！
